/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { C12DAO } from "./C12DAO";
export type { C12DAOGovernor } from "./C12DAOGovernor";
export type { C12DAOStaking } from "./C12DAOStaking";
export type { C12DAOTimelock } from "./C12DAOTimelock";
export type { C12DAOTreasury } from "./C12DAOTreasury";
