# Simplified Cloud Build configuration for initial deployment
steps:
  # Step 1: Install dependencies
  - name: 'node:20-alpine'
    id: 'install-deps'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing pnpm..."
        npm install -g pnpm@8.15.0
        echo "Installing dependencies..."
        pnpm install --frozen-lockfile
        echo "Compiling contracts..."
        pnpm compile

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/c12ai-dao/c12usd-repo/c12usd-backend:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/c12ai-dao/c12usd-repo/c12usd-backend:latest'
      - '.'

  # Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/c12ai-dao/c12usd-repo/c12usd-backend'

  # Step 4: Deploy to Cloud Run (staging)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-staging'
    args:
      - 'run'
      - 'deploy'
      - 'c12usd-backend-staging'
      - '--image=us-central1-docker.pkg.dev/c12ai-dao/c12usd-repo/c12usd-backend:${BUILD_ID}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--concurrency=1000'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--execution-environment=gen2'
      - '--service-account=c12usd-production-cloudrun@c12ai-dao.iam.gserviceaccount.com'
      - '--set-env-vars=NODE_ENV=staging'
      - '--set-secrets=BSC_RPC=bsc_rpc_url:latest,POLYGON_RPC=polygon_rpc_url:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'