# C12USD Security Configuration
# Comprehensive security settings for production deployment

security:
  # Authentication & Authorization
  auth:
    # JWT Token settings
    jwt:
      secret_key: ${JWT_SECRET}
      expires_in: "24h"
      refresh_expires_in: "7d"
      algorithm: "HS256"
      issuer: "c12usd-api"
      audience: "c12usd-users"

    # Session management
    session:
      timeout_hours: 24
      max_concurrent_sessions: 5
      idle_timeout_minutes: 60
      secure_cookies: true
      same_site: "strict"

    # Multi-factor authentication
    mfa:
      enabled: true
      required_for_admin: true
      required_for_high_value: true
      high_value_threshold: 10000
      backup_codes_count: 10

  # Rate Limiting
  rate_limiting:
    # API endpoints
    api:
      global:
        window_minutes: 60
        max_requests: 1000
      authentication:
        window_minutes: 15
        max_requests: 5
      mint_operations:
        window_minutes: 60
        max_requests: 10
      redeem_operations:
        window_minutes: 60
        max_requests: 5
      kyc_submission:
        window_minutes: 1440  # 24 hours
        max_requests: 3

    # IP-based limiting
    ip_limiting:
      enabled: true
      blacklist_threshold: 100
      blacklist_duration_hours: 24
      whitelist_admin_ips: []

  # Input Validation
  validation:
    # Address validation
    ethereum_address:
      regex: "^0x[a-fA-F0-9]{40}$"
      checksum_required: false

    # Amount validation
    transaction_amounts:
      min_mint_usd: 1.00
      max_mint_usd: 100000.00
      min_redeem_usd: 1.00
      max_redeem_usd: 100000.00
      decimal_places: 6

    # File upload validation
    file_uploads:
      max_size_mb: 5
      allowed_types:
        - "image/jpeg"
        - "image/png"
        - "image/gif"
        - "application/pdf"
      virus_scanning: true

  # Encryption
  encryption:
    # Data at rest
    database:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation_days: 90

    # Data in transit
    tls:
      min_version: "1.3"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
      hsts_max_age: 31536000

    # Sensitive field encryption
    pii_encryption:
      enabled: true
      fields:
        - "email"
        - "phone_number"
        - "kyc_documents"
        - "payment_details"

  # Access Control
  access_control:
    # Role-based permissions
    rbac:
      enabled: true
      default_role: "user"
      roles:
        admin:
          - "all_permissions"
        compliance_officer:
          - "view_kyc_documents"
          - "approve_kyc"
          - "view_compliance_reports"
          - "manage_user_status"
        treasury_manager:
          - "view_reserves"
          - "manage_treasury_operations"
          - "view_financial_reports"
        support_agent:
          - "view_user_profiles"
          - "assist_users"
          - "view_transaction_history"

    # IP whitelisting for admin functions
    admin_ip_whitelist:
      enabled: false  # Set to true and populate with IPs in production
      addresses: []

  # Audit & Monitoring
  audit:
    # Logging configuration
    logging:
      level: "info"
      format: "json"
      retention_days: 365
      sensitive_data_masking: true

    # Events to audit
    audit_events:
      - "user_login"
      - "user_logout"
      - "failed_login_attempt"
      - "password_change"
      - "mint_request"
      - "redeem_request"
      - "kyc_submission"
      - "admin_action"
      - "config_change"
      - "security_alert"

    # Real-time monitoring
    monitoring:
      failed_login_threshold: 5
      suspicious_activity_threshold: 10
      high_risk_transaction_threshold: 50000
      alert_channels:
        - "slack"
        - "email"
        - "pagerduty"

# Compliance Configuration
compliance:
  # KYC/AML Settings
  kyc:
    required: true
    tiers:
      tier_0:
        max_transaction_usd: 1000
        monthly_limit_usd: 5000
        required_documents: []
      tier_1:
        max_transaction_usd: 10000
        monthly_limit_usd: 50000
        required_documents:
          - "government_id"
          - "proof_of_address"
      tier_2:
        max_transaction_usd: 100000
        monthly_limit_usd: 500000
        required_documents:
          - "government_id"
          - "proof_of_address"
          - "selfie"
          - "enhanced_due_diligence"

  # AML (Anti-Money Laundering)
  aml:
    transaction_monitoring:
      enabled: true
      suspicious_patterns:
        - "rapid_succession"
        - "round_dollar_amounts"
        - "structuring_behavior"
        - "high_risk_country"

    risk_scoring:
      enabled: true
      factors:
        - "geographic_risk"
        - "transaction_patterns"
        - "user_behavior"
        - "network_analysis"
      thresholds:
        low_risk: 25
        medium_risk: 50
        high_risk: 75

  # Sanctions Screening
  sanctions:
    enabled: true
    providers:
      - "ofac"
      - "eu_sanctions"
      - "un_sanctions"
    screening_frequency: "real_time"
    match_threshold: 85

  # Regulatory Reporting
  reporting:
    ctr_threshold_usd: 10000  # Currency Transaction Report
    sar_enabled: true         # Suspicious Activity Report
    fatca_enabled: true       # Foreign Account Tax Compliance Act
    gdpr_compliance: true     # General Data Protection Regulation

# Disaster Recovery & Business Continuity
disaster_recovery:
  # Backup Configuration
  backups:
    frequency: "daily"
    retention_period_days: 90
    encryption: true
    verification: true
    offsite_storage: true

  # Failover Configuration
  failover:
    enabled: true
    rto_minutes: 15    # Recovery Time Objective
    rpo_minutes: 5     # Recovery Point Objective
    health_check_interval: 30

  # Circuit Breaker
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_time_seconds: 30
    services:
      - "mint_service"
      - "redeem_service"
      - "kyc_service"
      - "payment_processing"

# API Security
api_security:
  # CORS Configuration
  cors:
    allowed_origins:
      - "https://c12usd.com"
      - "https://app.c12usd.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "X-Requested-With"
    max_age: 86400

  # Content Security Policy
  csp:
    default_src: "'self'"
    script_src: "'self' 'unsafe-inline'"
    style_src: "'self' 'unsafe-inline'"
    img_src: "'self' data: https:"
    connect_src: "'self' https://api.c12usd.com"

  # Request signing (for high-value operations)
  request_signing:
    enabled: true
    algorithm: "ECDSA"
    required_for:
      - "treasury_operations"
      - "admin_actions"
      - "high_value_transactions"

# Third-party integrations security
integrations:
  stripe:
    webhook_verification: true
    endpoint_secret: ${STRIPE_WEBHOOK_SECRET}

  cashapp:
    webhook_verification: true
    endpoint_secret: ${CASHAPP_WEBHOOK_SECRET}

  chainlink:
    node_authentication: true
    request_timeout_seconds: 30

  layerzero:
    message_verification: true
    trusted_remotes_only: true