/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockLayerZeroEndpoint,
  MockLayerZeroEndpointInterface,
} from "../../../contracts/mocks/MockLayerZeroEndpoint";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oapp",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegate",
        type: "address",
      },
    ],
    name: "DelegateSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "delegates",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_oapp",
        type: "address",
      },
    ],
    name: "getDelegate",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_delegate",
        type: "address",
      },
    ],
    name: "setDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610272806100206000396000f3fe60806040526004361061003f5760003560e01c8063544d856414610044578063587cde1e146100995780637f0a3bf9146100cf578063ca5eb5e1146100e5575b600080fd5b34801561005057600080fd5b5061007d61005f366004610157565b6001600160a01b039081166000908152602081905260409020541690565b6040516001600160a01b03909116815260200160405180910390f35b3480156100a557600080fd5b5061007d6100b4366004610157565b6000602081905290815260409020546001600160a01b031681565b6100e36100dd3660046101d0565b50505050565b005b3480156100f157600080fd5b506100e3610100366004610157565b3360008181526020819052604080822080546001600160a01b0319166001600160a01b03861690811790915590519092917f6ee10e9ed4d6ce9742703a498707862f4b00f1396a87195eb93267b3d798398191a350565b60006020828403121561016957600080fd5b81356001600160a01b038116811461018057600080fd5b9392505050565b60008083601f84011261019957600080fd5b50813567ffffffffffffffff8111156101b157600080fd5b6020830191508360208285010111156101c957600080fd5b9250929050565b600080600080604085870312156101e657600080fd5b843567ffffffffffffffff808211156101fe57600080fd5b61020a88838901610187565b9096509450602087013591508082111561022357600080fd5b5061023087828801610187565b9598949750955050505056fea264697066735822122024efbe46cb5fbb3b3edfdc1cc6f226311442679891dcd6f72d6391b10eec341b64736f6c63430008180033";

type MockLayerZeroEndpointConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockLayerZeroEndpointConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockLayerZeroEndpoint__factory extends ContractFactory {
  constructor(...args: MockLayerZeroEndpointConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MockLayerZeroEndpoint> {
    return super.deploy(overrides || {}) as Promise<MockLayerZeroEndpoint>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockLayerZeroEndpoint {
    return super.attach(address) as MockLayerZeroEndpoint;
  }
  override connect(signer: Signer): MockLayerZeroEndpoint__factory {
    return super.connect(signer) as MockLayerZeroEndpoint__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockLayerZeroEndpointInterface {
    return new utils.Interface(_abi) as MockLayerZeroEndpointInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockLayerZeroEndpoint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockLayerZeroEndpoint;
  }
}
