/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockFlashBorrower } from "./MockFlashBorrower";
export type { MockLayerZeroEndpoint } from "./MockLayerZeroEndpoint";
